/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/{knowledge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge */
        get: operations["get_knowledge_knowledge__knowledge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/{knowledge_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Knowledge History */
        get: operations["get_knowledge_history_knowledge__knowledge_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Decisions */
        get: operations["get_decisions_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get People */
        get: operations["get_people_people_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conflicts */
        get: operations["get_conflicts_conflicts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context */
        get: operations["get_context_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/context/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context Product */
        get: operations["get_context_product_context_product_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/context/customer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context Customer */
        get: operations["get_context_customer_context_customer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/context/strategy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context Strategy */
        get: operations["get_context_strategy_context_strategy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/{knowledge_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Knowledge */
        post: operations["approve_knowledge_knowledge__knowledge_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/{knowledge_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Knowledge */
        post: operations["reject_knowledge_knowledge__knowledge_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/knowledge/{knowledge_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit Knowledge */
        post: operations["edit_knowledge_knowledge__knowledge_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * KnowledgeEditRequest
         * @description Fields a human reviewer can edit before a proposed record goes
         *     active (PRD §17/§20). Only the fields a human plausibly corrects by
         *     hand for MVP - not every KnowledgeRecord field is open to editing here
         *     (e.g. status has its own approve/reject routes, ids/timestamps aren't
         *     editable at all).
         */
        KnowledgeEditRequest: {
            /** Edited By */
            edited_by: string;
            /** Statement */
            statement?: string | null;
            /** Topic */
            topic?: string | null;
            /** Confidence */
            confidence?: number | null;
        };
        /**
         * KnowledgeRecord
         * @description A single unit of organisational knowledge (PRD §7).
         */
        KnowledgeRecord: {
            /** Id */
            id: string;
            type: components["schemas"]["KnowledgeType"];
            /** Topic */
            topic: string;
            /** Statement */
            statement: string;
            status: components["schemas"]["KnowledgeStatus"];
            /** Confidence */
            confidence: number;
            /** Source Ids */
            source_ids: string[];
            /** People */
            people: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Last Updated At
             * Format: date-time
             */
            last_updated_at: string;
            /** Supersedes */
            supersedes?: string | null;
            /** Superseded At */
            superseded_at?: string | null;
            /**
             * Conflicts With
             * @default []
             */
            conflicts_with: string[];
            /**
             * Workspace Id
             * @default default
             */
            workspace_id: string;
            /**
             * Source Id
             * @default unspecified
             */
            source_id: string;
            /**
             * Visibility
             * @default internal
             */
            visibility: string;
            /** Owner */
            owner?: string | null;
            /**
             * Access Level
             * @default standard
             */
            access_level: string;
            /** Edited By */
            edited_by?: string | null;
        };
        /** KnowledgeRecordWithSources */
        KnowledgeRecordWithSources: {
            /** Id */
            id: string;
            type: components["schemas"]["KnowledgeType"];
            /** Topic */
            topic: string;
            /** Statement */
            statement: string;
            status: components["schemas"]["KnowledgeStatus"];
            /** Confidence */
            confidence: number;
            /** Source Ids */
            source_ids: string[];
            /** People */
            people: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Last Updated At
             * Format: date-time
             */
            last_updated_at: string;
            /** Supersedes */
            supersedes?: string | null;
            /** Superseded At */
            superseded_at?: string | null;
            /**
             * Conflicts With
             * @default []
             */
            conflicts_with: string[];
            /**
             * Workspace Id
             * @default default
             */
            workspace_id: string;
            /**
             * Source Id
             * @default unspecified
             */
            source_id: string;
            /**
             * Visibility
             * @default internal
             */
            visibility: string;
            /** Owner */
            owner?: string | null;
            /**
             * Access Level
             * @default standard
             */
            access_level: string;
            /** Edited By */
            edited_by?: string | null;
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["Source"][];
        };
        /**
         * KnowledgeStatus
         * @enum {string}
         */
        KnowledgeStatus: "active" | "superseded" | "conflicting" | "pending_review" | "rejected";
        /**
         * KnowledgeType
         * @enum {string}
         */
        KnowledgeType: "decision" | "fact" | "customer_insight" | "strategy" | "product_requirement" | "process" | "policy" | "person" | "ownership" | "action" | "hypothesis" | "conflict";
        /**
         * Source
         * @description One piece of provenance for a knowledge record - PRD's "show the
         *     meetings supporting each memory" (§16.C), not the raw transcript id.
         */
        Source: {
            /** Meeting Title */
            meeting_title: string;
            /**
             * Meeting Date
             * Format: date-time
             */
            meeting_date: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_knowledge_knowledge__knowledge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecordWithSources"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_knowledge_history_knowledge__knowledge_id__history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_decisions_decisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"][];
                };
            };
        };
    };
    get_people_people_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"][];
                };
            };
        };
    };
    get_conflicts_conflicts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"][];
                };
            };
        };
    };
    get_context_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"][];
                };
            };
        };
    };
    get_context_product_context_product_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"][];
                };
            };
        };
    };
    get_context_customer_context_customer_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"][];
                };
            };
        };
    };
    get_context_strategy_context_strategy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"][];
                };
            };
        };
    };
    approve_knowledge_knowledge__knowledge_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_knowledge_knowledge__knowledge_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_knowledge_knowledge__knowledge_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
